# student_names.py

student_names = [
    "Aaiza Khan",
    "Aasma Raza",
    "Abdul Ahad Shah Warsi",
    "Abdul Aziz",
    "Abdul Basit Khan",
    "Abdul Latif",
    "Abdul Qadeer Khan",
    "Abdul Raheem",
    "Abdul Rahman",
    "Abdul Rasheed",
    "Abdul Razzaq",
    "Abdul Rehman",
    "Abdul Sajjad",
    "Abdul Sattar",
    "Abdul Tawwab",
    "Abdul Waheed",
    "Abdullah Siddiqui",
    "Abida Bano ",
    "Ahmed Zia Matloob",
    "Aiman",
    "Aiman Hassan",
    "Aiman Siddiqui",
    "Aisha",
    "Aisha Abdul Rasheed",
    "Aisha Aziz",
    "Akmal Khan",
    "Aleem Ahmed Khan",
    "Aleem Ullah",
    "Alia Kanwal",
    "Alif Khan Hassan Zai",
    "Aliza Saleem",
    "Allauddin",
    "Almas",
    "Alsa Baig",
    "Amjad Hussain",
    "Amna Abdul Rasheed",
    "Amna Usmani",
    "Aneela Batool",
    "Aneeqa Sirhandi",
    "Anis Ahmed Siddiqui",
    "Anosha Mukhtar",
    "Anshrah Zainab",
    "Anum",
    "Anum Mukhtar",
    "Anum Naz",
    "Anusha Javeed",
    "Aqsa Aslam",
    "Aqsa Jawed",
    "Aqsa Kanwal",
    "Aqsa Khan",
    "Areeba Abbas",
    "Areeba Ansari",
    "Ariba Saleem",
    "Asfia",
    "Ashhad Ul Hassan",
    "Ashiq Ali",
    "Asif Ahmed Khan",
    "Aslam Pervez",
    "Asma Khan",
    "Asma Masood Aziz",
    "Atrouba Qureshi",
    "Ayaz Ahmed",
    "Ayaz Khan",
    "Ayesha Atique",
    "Ayesha Binte Talib ",
    "Ayesha Fatima",
    "Ayesha Kanwal Saeed",
    "Ayesha Niaz",
    "Ayesha Zubair",
    "Ayliya Waqar",
    "Aziz Ur Rehman",
    "Baneen Aisha",
    "Bilquees Paras",
    "Birjees Ashraf",
    "Bisma Afzal",
    "Bisma Hayat",
    "Bisma Imran Siddiqui",
    "Bushra Khalid",
    "Deep Fatima Rizvi",
    "Diya",
    "Doha Wissal",
    "Dua Fatima",
    "Era Fatima",
    "Esha Tur Radia",
    "Fabiha",
    "Faiq Rizwan",
    "Faiza Dure Shawar",
    "Faiza Kamran",
    "Fakiha",
    "Farhat Perveen",
    "Farheen Zakir",
    "Faria Aijaz",
    "Fariha Khan",
    "Fariya Iqbal",
    "Fatima Ali",
    "Fatima Attaria",
    "Fatima Mehtab",
    "Fatima Shair Ali",
    "Fatima Siddiqui",
    "Fayyaz Ahmed",
    "Fazal Ghani Khan",
    "Fizza Khan",
    "Fizza Rashid",
    "Ghania Fatima",
    "Ghazala Asfreen",
    "Ghulam Asghar",
    "Ghulam Nabi",
    "Ghulam Sajjad",
    "Ghulam Yaseen Urf Gulfam",
    "Goher Ali Shaikh",
    "Gulaab Khan",
    "Gulafshan",
    "Gulfam Ahed",
    "Habiba Jaweed",
    "Hadia Ahmed",
    "Hadiqa Khan",
    "Hafiza Hareem Mehmood",
    "Hafiza Narmeen Manzoor",
    "Hafsa Fatima",
    "Hafsa Kamran",
    "Hafsa Latif",
    "Hafsa Shahzad Ul Hassan",
    "Hafsa Shakeel ",
    "Hafsa Waheed",
    "Haji Siddique Ahmed Khan",
    "Hamid Mehmood",
    "Hamna Aslam",
    "Hayat Muhammad",
    "Hina Khan",
    "Hina Rafique",
    "Hina Saeed",
    "Hooria Qadri",
    "Huma Liaquat Ali",
    "Huma Shafique",
    "Hussam Haider",
    "Ibrahim Qadri",
    "Iffat Khan",
    "Ifra",
    "Iftikhar Ali",
    "Ikram Ul Hassan",
    "Imran Baig",
    "Inamul Hasan Ansary",
    "Insha Aleem",
    "Iqbal Javeed",
    "Iqra Abdul Razzaq",
    "Iqra Rafiq",
    "Iqra Sabir",
    "Irfan Ullah Siddiqui",
    "Irshad Ahmad Khan",
    "Ishrat Jahan",
    "Islam Ud Din",
    "Jalal Jamil",
    "Jane Alam",
    "Jasim",
    "Javed Alam",
    "Javed Iqbal",
    "Javeria Aleem",
    "Javeria Ayaz",
    "Javeria Elahi",
    "Javeria Mehak",
    "Jawed Akhter",
    "Jumma Khan Babar",
    "Kainat Javed",
    "Kamran Irshad Qureshi",
    "Kamran Shahzad Butt",
    "Kanwal Zamir",
    "Kanza Zehra Naqvi",
    "Khadija Hamid",
    "Khadija Mehtab",
    "Khadija Noor",
    "Khadija Quddusi",
    "Khair Zaman",
    "Khalid Hussain",
    "Khalid Nasir Siddiqui",
    "Khaliq Ur Rehman Khan",
    "Khizra Nasir Khan",
    "Khurram",
    "Khuwaja Ashfaq Ahmed",
    "Kifayat Khan",
    "Kishwer Mahtab",
    "Komal Irfan",
    "Kubra Fatima",
    "Laiba Liaqat",
    "Laila Mumtaz",
    "Latif Ahmed",
    "Liaqat Ali",
    "Lubna Khalid Siddiqui",
    "Madiha Nida",
    "Maha Arshad",
    "Maha Batool",
    "Maha Farooq",
    "Maha Irfan",
    "Maham Aijaz",
    "Maham Iftikhar",
    "Maham Jabeen",
    "Mahfooz Ahmed Shariff",
    "Mahmood Akhter",
    "Mahrukh",
    "Mahrukh Shujaat",
    "Mahwish Fatima",
    "Maimoona Masood Ferozi",
    "Malaika Islam",
    "Malaika Sheikh",
    "Malik Javed",
    "Manahil Shareef",
    "Mansoor Ahmed",
    "Maqsood Ahmed",
    "Maria Ahad",
    "Maria Ansari",
    "Maria Hassan Rana",
    "Maria Jalal",
    "Maria Noman",
    "Mario Angelo Rodrigues",
    "Mariyam Bukhari",
    "Maryam Jamshaid",
    "Maryam Jamal",
    "Maryam Ibrahim",
    "Maryam Iqbal",
    "Maryam Nadeem",
    "Maryam Shaukat",
    "Masood Ahmed Hashmi",
    "Masood Ali Rizvi",
    "Masood Aziz",
    "Masroor Ul Haq",
    "Mehak Khurram",
    "Mehak Sultan Ali Noorani",
    "Mehmood Ahmed Qureshi",
    "Mehmood Ali",
    "Mehreen Naz",
    "Mehru Un Nisa Bibi",
    "Mehtab Ahmed",
    "Mehtab Uddin",
    "Merry Shahzad",
    "Mirza Haider Baig",
    "Misbah Fayyaz",
    "Mohammad Afzal Khan",
    "Mohammad Aslam",
    "Mohammad Khalid",
    "Mohsin Raza",
    "Moin Khan",
    "Muhammad Abdul Imran Siddiqui",
    "Muhammad Abdul Wajid",
    "Muhammad Afaq",
    "Muhammad Ahmed",
    "Muhammad Ahsan Alvi",
    "Muhammad Aijaz",
    "Muhammad Akram",
    "Muhammad Ali",
    "Muhammad Ali Abbas",
    "Muhammad Ali Qureshi",
    "Muhammad Amin",
    "Muhammad Anwer Khan",
    "Muhammad Arif Sheikh",
    "Muhammad Arshad Khan",
    "Muhammad Ashraf",
    "Muhammad Asif Anwar",
    "Muhammad Aslam Qureshi",
    "Muhammad Atique Ahmed",
    "Muhammad Ayoub Mughal",
    "Muhammad Ayub ",
    "Muhammad Azeem Siddiqui",
    "Muhammad Daniyal Siddiqui",
    "Muhammad Dilshad Khan",
    "Muhammad Ejaz Azeemi",
    "Muhammad Farooq",
    "Muhammad Farooq Khan",
    "Muhammad Hasib",
    "Muhammad Hussain",
    "Muhammad Iqbal",
    "Muhammad Iqbal Pervaiz",
    "Muhammad Irfan",
    "Muhammad Israr",
    "Muhammad Jamil",
    "Muhammad Jamshad Khan",
    "Muhammad Javed",
    "Muhammad Kamal",
    "Muhammad Khalid",
    "Muhammad Mahmood Usmani",
    "Muhammad Manzoor",
    "Muhammad Mohsin Khan",
    "Muhammad Mujtaba Saleem",
    "Muhammad Munir Alvi",
    "Muhammad Nadeem Khan",
    "Muhammad Nafees Khan",
    "Muhammad Naseer",
    "Muhammad Nazeer",
    "Muhammad Nazim",
    "Muhammad Qasim",
    "Muhammad Rafiq Ahmed",
    "Muhammad Rashid Qureshi",
    "Muhammad Rauf Ahmed",
    "Muhammad Rauf Kamal",
    "Muhammad Raza",
    "Muhammad Sabir Hanif",
    "Muhammad Saeed",
    "Muhammad Saleem",
    "Muhammad Shakeel Ahmed",
    "Muhammad Sheraz",
    "Muhammad Shujaat Ullah Sharif",
    "Muhammad Suleman Ansari",
    "Muhammad Usman Siddiqui",
    "Muhammad Yakoob Mirza",
    "Muhammad Yameen Khan",
    "Muhammad Younas",
    "Muhammad Yousuf",
    "Muhammad Zahid Khan",
    "Muhammad Zakir",
    "Muhammed Iqbal",
    "Mukhtar Ahmed",
    "Mukhtar Ahmed Naseem",
    "Mukhtar Ahmed Rao",
    "Mulaika Sajid",
    "Mumtaz Khan Khattak",
    "Munawar Khan Qadri",
    "Muqaddas Afaq",
    "Musarrat Hasib",
    "Muskan Khan",
    "Mustafa Kamal",
    "Nadeem Laiq",
    "Nadeem Ahmed",
    "Nadeem Izhar",
    "Nafees Fatima",
    "Naila Sadaf",
    "Nasir Khan",
    "Nasir Habib",
    "Nasireen",
    "Nazeer Khan",
    "Nazeer Hussain",
    "Nazish Siraj",
    "Neelum Waqar",
    "Niaz Ud Din",
    "Nimra Hashmi",
    "Nimra Nazim",
    "Nisar Ahmed",
    "Nisma Javed",
    "Noman Ahmed",
    "Noor Alam",
    "Noor Rehman",
    "Noor Ul Ain",
    "Noor Ul Huda",
    "Noor Ul Islam",
    "Nuzhat Khadija",
    "Panda Khan Babar",
    "Patrick John Rodrigues",
    "Muhammad Mazhar Quddusi",
    "Qamar Uz Zaman",
    "Qari Muhammad Abdullah",
    "Qazi Bashir Ahmed",
    "Qirat Ali",
    "Quratulain",
    "Rabia",
    "Rabia Nasir",
    "Rabia Ramzan",
    "Rabia Shafiq",
    "Rabia Yaseen",
    "Rafey Ahmed",
    "Rafia Iqbal",
    "Rafiah Kamran",
    "Rais Ahmed",
    "Ramisa Saleem",
    "Ramla Khan",
    "Ramsha Khan",
    "Ramzan",
    "Rasheed Ahmed",
    "Rashid Ali",
    "Rashid Khan",
    "Razi Ul Azhar",
    "Razia Hijab",
    "Rida Batool",
    "Rida Fatima",
    "Roomaisa Javed",
    "Roshan Mohamid",
    "Rukhsar Alam",
    "Ruqia",
    "Rutaba Asif",
    "Saba Alvi",
    "Saba Rasheed",
    "Saba Tariq",
    "Sabir Ali Hussain",
    "Saboor Ahmed",
    "Sadia Ejaz Azeemi",
    "Sadia Siddiqui",
    "Saeed Ahmed Qureshi",
    "Safina Baig",
    "Safina Kamran",
    "Sajia Ali",
    "Sajjad Hussain",
    "Saleem",
    "Saleem Raza",
    "Saleem Shah",
    "Salma Salman",
    "Salman Ahmed",
    "Salman Nasir",
    "Salman Ghani Khan",
    "Salman Sabir Ali Khan Sherwani",
    "Sameea Mirza",
    "Sameera Sajjad",
    "Samina Sabir",
    "Samira Rashid Khan",
    "Samiya Mirza",
    "Samrin Siddique",
    "Samuel Shahzad",
    "Sana",
    "Saniya Salman",
    "Saniya Mohsin",
    "Sanober Naz",
    "Sara",
    "Sarosh Khan",
    "Sarwer Elahi",
    "Savera Ayoub Mughal",
    "Sehreen Mehak",
    "Sehrish Khan",
    "Shabih Nadeem",
    "Shafiq Ahmed",
    "Shah Fareen",
    "Shahbaz Ali",
    "Shahid Baig",
    "Shahid Mehmood",
    "Shahzad Ali Muhammad",
    "Shahzad Ul Hassan",
    "Shaikh Wissal Ud Din",
    "Shaila Mehmood",
    "Shair Ali",
    "Shaista Perveen Shaikh",
    "Shakeel Shafi",
    "Shakila Qurashi",
    "Shama",
    "Sharmeen Naseer",
    "Shaukat",
    "Sheeza Tauqir",
    "Sheikh Jaweed Alam",
    "Sheikh Muhammad Kamran",
    "Sheikh Muhammad Shafique",
    "Sheikh Noor Ul Islam",
    "Sheikh Sanam",
    "Shoaib",
    "Shumaila Jabeen",
    "Shumaila Rafiq",
    "Siraj Ud din",
    "Soaiba Salman",
    "Sobia Irfan",
    "Sobia Naz",
    "Sonia William",
    "Subhata Rasheed",
    "Sughra Shair Ali",
    "Suheera Tanveer",
    "Sultan Ali Noorani",
    "Sumaira Kauser",
    "Sumaira Kauser ",
    "Sumaira Raheem",
    "Sumama Shoaib",
    "Sumbul Fatima",
    "Sumbul Khalid",
    "Sundus Ahmed",
    "Syed Ahmed Bukhari",
    "Syed Athar Hussain Zaidi",
    "Syed Ayaz Ali Rehmani",
    "Syed Baqar Jaffri",
    "Syed Farhat Hussain Jaffri",
    "Syed Ghulam Abbas Naqvi",
    "Syed Ibne Hasan Naqvi",
    "Syed Imran Iqbal Shah",
    "Syed Jamshaid Ali Sherazi",
    "Syed Kamran Azeem",
    "Syed Khalid Kazmi",
    "Syed Manzar Hasan",
    "Syed Manzar Hasnain Naqvi",
    "Syed Maria Hasan",
    "Syed Muhammad Abbas",
    "Syed Muhammad Ghufran Hashmi",
    "Syed Muhammad Haroon Pirzada",
    "Syed Muhammad Hassan",
    "Syed Muhammad Imran",
    "Syed Muhammad Kamran",
    "Syed Muhammad Mukhtar",
    "Syed Nadir Abbas",
    "Syed Nasir Mehdi",
    "Syed Raees Abbas Naqvi",
    "Syed Raees Abbas Jaffery",
    "Syed Rashid Ali",
    "Syed Sajid Jafar",
    "Syed Sanawar Ali",
    "Syed Tanveer Ali",
    "Syed Waqar Ali Jaffri",
    "Syed Zaheer Abbas Naqvi",
    "Syed Zakir Hussain Rizvi",
    "Syed Zeeshan Haider",
    "Syeda Alishba Mohsin",
    "Syeda Amna",
    "Syeda Anusha Azeem",
    "Syeda Farwa Fatima Naqvi",
    "Syeda Fatima Hasan",
    "Syeda Fizza Fatima Naqvi",
    "Syeda Hassan Ali Shah Bukhari",
    "Syeda Hira Pirzada",
    "Syeda Ishfa Zehra",
    "Syeda Javeria Imran",
    "Syeda Kainat Jamshaid",
    "Syeda Kulsoom Abbas",
    "Syeda Mahe Umam",
    "Syeda Mahnoor Fatima",
    "Syeda Maliha",
    "Syeda Minhal Naqvi",
    "Syeda Saher Zeeshan",
    "Syeda Sani Zehra Rizvi",
    "Syeda Shiza Hassan Bukhari",
    "Syeda Tahreem Kazmi",
    "Syeda Wahid Ali",
    "Syeda Wajeeha Batool",
    "Syeda Zainab Abbas",
    "Tabina Sattar",
    "Tahir Hasan",
    "Tahira Iqbal",
    "Tahira Noor",
    "Tahsheem",
    "Talat Hashmi",
    "Talib Hussain",
    "Talib Rasool",
    "Tamkanat Khalid",
    "Tania",
    "Tariq Zahid",
    "Tasneem Yousuf",
    "Tauqir Hussain",
    "Tazeen Fatima",
    "Tehreem Khan",
    "Tooba Zafar",
    "Tooba Zia Khan",
    "Tuba Khan",
    "Tuba Moin",
    "Tuba Zehra",
    "Ummeha Bux",
    "Unzah Rais",
    "Unzila Masroor",
    "Urooba Kamal",
    "Waheed Ur Rehman",
    "Waqar Ahmed",
    "Warda Mehtab",
    "Warda Nadeem",
    "Warda Younas",
    "Wardah Saleem",
    "William",
    "Yamna Maqsood",
    "Yawar Abbas",
    "Yousuf Ali",
    "Yousuf Noman",
    "Yumna Mahmood",
    "Zafar Munir Ansari",
    "Zaheer Ud Din",
    "Zahid Akhtar",
    "Zahid Ali",
    "Zain Ul Abedin",
    "Zainab Ali",
    "Zainab Fatima",
    "Zakia Nazeer",
    "Zakia Nisar",
    "Zamir Ahmed Khan",
    "Zamir Uddin Qureshi",
    "Zara Akram",
    "Zarlashta",
    "Zawata",
    "Zeenat Bibi",
    "Zia Barkat",
    "Zohaib Ahmed Naseem",
    "Zubair Ahmed",
    "Zubair Khan",
    "Zubair Mohsin",
    "Zubia Ayaz",
    "Zulfiqar Ali",
    "Zunaira Aziz",
]
