subjects_pool = [
    "Accounting",
    "Applied Chemistry",
    "Biology",
    "Business Studies",
    "Chemistry",
    "Child Development",
    "Child Psychology",
    "Classroom Assessment",
    "Classroom Management",
    "Communication Skills",
    "Comparative Education",
    "Compiler Construction",
    "Computer Literacy",
    "Computer Science",
    "Contemporary Issues",
    "Critical Thinking",
    "Curriculum Development",
    "Economics",
    "English Grammar",
    "English Literature",
    "Environmental Chemistry",
    "General Method of Teaching",
    "General Science",
    "Geography",
    "History",
    "Inclusive Education",
    "Information and Communication Technologies",
    "Inorganic Chemistry",
    "Introduction to Algorithm",
    "Islamic Studies",
    "Law",
    "Mathematics",
    "Organic Chemistry",
    "Pakistan Studies",
    "Pakistan Studies",
    "Philosophy",
    "Physics",
    "Psychology",
    "Research Methodology",
    "School Management",
    "School, Communities and Teachers",
    "Sindhi",
    "Sociology",
    "Statistics",
    "Statistics",
    "Teaching of English",
    "Teaching of Mathematics",
    "Teaching of Science",
    "Teaching of Urdu",
    "Test Development",
    "Theory of Automata",
    "Urdu Poetry"
    "Urdu",
    "Urdu Literature"
]
